export const COMPETITION_WORKSPACE_SECTIONS = [
  {
    id: 'setup',
    label: 'Configuración',
    shortLabel: 'Config',
    group: 'config',
    description: 'Base, registro, divisiones y pagos.',
    primaryAction: 'Configurar competencia',
  },
  {
    id: 'launch',
    label: 'Lanzamiento',
    shortLabel: 'Lanzamiento',
    group: 'config',
    description: 'Revisar si ya esta lista y publicarla.',
    primaryAction: 'Lanzar competencia',
  },
  {
    id: 'enrollments',
    label: 'Inscripciones',
    shortLabel: 'Inscripciones',
    group: 'operacion',
    description: 'Inscritos y respuestas del registro.',
    primaryAction: 'Gestionar inscripciones',
  },
  {
    id: 'ticketing',
    label: 'Boleteria',
    shortLabel: 'Boleteria',
    group: 'operacion',
    description: 'Boletas, ordenes y escaneo de ingreso.',
    primaryAction: 'Gestionar boleteria',
  },
  {
    id: 'discounts',
    label: 'Descuentos',
    shortLabel: 'Descuentos',
    group: 'operacion',
    description: 'Codigos de descuento con limite de usos y log.',
    primaryAction: 'Gestionar descuentos',
  },
  {
    id: 'invitations',
    label: 'Invitaciones',
    shortLabel: 'Invitaciones',
    group: 'operacion',
    description: 'Invita competidores por email sin pasarela de pago.',
    primaryAction: 'Gestionar invitaciones',
  },
  {
    id: 'prep',
    label: 'Preparación',
    shortLabel: 'Preparación',
    group: 'operacion',
    description: 'Heats, cronograma y salida.',
    primaryAction: 'Preparar competencia',
  },
  {
    id: 'live',
    label: 'En vivo',
    shortLabel: 'En vivo',
    group: 'operacion',
    description: 'Resultados y control en competencia.',
    primaryAction: 'Operar en vivo',
  },
  {
    id: 'broadcast',
    label: 'Pantalla',
    shortLabel: 'Pantalla',
    group: 'publico',
    description: 'Salida publica y vista externa.',
    primaryAction: 'Abrir pantalla',
  },
]

export const COMPETITION_WORKSPACE_DEFAULT_SECTION = 'setup'
